### ISSUE TITLE
frap install Error

### ISSUE THREAD

**Issue by larzknoke** [flippakitten/frap#25]
after `gem install frap` and `frap -version` I've got this error:

```
➜  ~ rvm use 2.6.5
Using /Users/xxxx/.rvm/gems/ruby-2.6.5
➜  ~ frap -version
Traceback (most recent call last):
	12: from /Users/xxxx/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
	11: from /Users/xxxx/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
	10: from /Users/xxxx/.rvm/gems/ruby-2.6.5/bin/frap:23:in `<main>'
	 9: from /Users/xxxx/.rvm/gems/ruby-2.6.5/bin/frap:23:in `load'
	 8: from /Users/xxxx/.rvm/gems/ruby-2.6.5/gems/frap-0.3.0/bin/frap:2:in `<top (required)>'
	 7: from /Users/xxxx/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /Users/xxxx/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /Users/xxxx/.rvm/gems/ruby-2.6.5/gems/frap-0.3.0/lib/frap.rb:7:in `<top (required)>'
	 4: from /Users/xxxx/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /Users/xxxx/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /Users/xxxx/.rvm/gems/ruby-2.6.5/gems/frap-0.3.0/lib/frap/generators/flutter_resource.rb:1:in `<top (required)>'
	 1: from /Users/xxxx/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/xxxx/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- active_support/inflector (LoadError)
```

**Comment by flippakitten** [comment]
@larzknoke Thanks for bringing this up.

Just to confirm, do you have rails 6.0.1 installed and running Bundler 2.0.2

If so, can you try doing:
`gem install activesupport`

**Comment by larzknoke** [comment]
I'm sorry, my fault, I forgot to install rails because I installed the a new ruby version with rvm. :/

Thx for your quick reply!

**Comment by flippakitten** [comment]
@larzknoke no worries, just glad you're sorted. Please do let me know if you have any other issues or ideas. Or even just let me know your feelings, or how I can improve things.
